<?php

namespace Database\Seeders\Region;

use App\Models\District;
use App\Models\Regency;
use App\Models\Village;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KapuasHuluSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $regency = Regency::create([
            'name' => 'Kabupaten Kapuas Hulu',
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $data = [
            'Badau' => [
                'Janting',
                'Kekurak',
                'Pulau Majang',
                'Sebindang',
                'Semuntik',
                'Seriang',
                'Tajum',
                'Tinting Seligi',
                'Badau',
            ],
            'Batang Lupar' => [
                'Labian',
                'Labian Ira`ang',
                'Lanjak Deras',
                'Melemba',
                'Mensiau',
                'Sepandan',
                'Setulang',
                'Sungai Abau',
                'Sungai Ajung',
                'Sungai Senunuk',
            ],
            'Bika' => [
                'Bika',
                'Bika Hulu',
                'Jelemuk',
                'Jongkong Manday',
                'Melapi Manday',
                'Nanga Manday',
                'Penyeluang',
                'Teluk Sindur',
            ],
            'Boyan Tanjung' => [
                'Boyan Tanjung',
                'Delintas Karya',
                'Karya Maju',
                'Landau Mentail',
                'Mujan',
                'Nanga Betung',
                'Nanga Boyan',
                'Nanga Danau',
                'Nanga Jemah',
                'Nanga Ret',
                'Nanga Sangan',
                'Pemawan',
                'Riam Mengelai',
                'Sri Wangi',
                'Teluk Geruguk',
                'Tubang Jaya',
            ],
            'Bunut Hilir' => [
                'Bunut Hilir',
                'Bunut Hulu',
                'Bunut Tengah',
                'Empangau',
                'Empangau Hilir',
                'Entibab',
                'Kapuas Raya',
                'Nanga Tuan',
                'Teluk Aur',
                'Tembang',
                'Ujung Pandang',
            ],
            'Bunut Hulu' => [
                'Bakong Permai',
                'Batu Tiga',
                'Beringin',
                'Nanga Dua',
                'Nanga Kelibang',
                'Nanga Payang',
                'Nanga Semangut',
                'Nanga Suruk',
                'Pantas Bersatu',
                'Riam Piyang',
                'Segitak',
                'Selaup',
                'Semangut Utara',
                'Sungai Besar',
                'Temuyuk',
            ],
            'Embaloh Hilir' => [
                'Belatung',
                'Keliling Semulung',
                'Kirin Nangka',
                'Lawik',
                'Nanga Embaloh',
                'Nanga Lauk',
                'Nanga Palin',
                'Pala Pintas',
                'Ujung Bayur',
            ],
            'Embaloh Hulu' => [
                'Banua Martinus',
                'Banua Ujung',
                'Batu Lintang',
                'Langan Baru',
                'Menua Sadap',
                'Pulau Manak',
                'Rantau Prapat',
                'Saujung Giling Manik',
                'Tamao',
                'Ulak Pauk',
            ],
            'Empanang' => [
                'Bajau Andai',
                'Keling Panggau',
                'Kumang Jaya',
                'Laja Sandang',
                'Nanga Kantuk',
                'Tintin Peninjau',
            ],
            'Hulu Gurung' => [
                'Beringin',
                'Bugang',
                'Karya Mandiri',
                'Kelakar',
                'Landau Kumpang',
                'Lubuk Antuk',
                'Mentawit',
                'Mubung',
                'Nanga Tepuai',
                'Nanga Yen',
                'Parang',
                'Sejahtera Mandiri',
                'Simpang Senara',
                'Tani Makmur',
                'Tunas Muda',
            ],
            'Jongkong' => [
                'Bontai',
                'Jongkong Kanan',
                'Jongkong Kiri Hilir',
                'Jongkong Kiri Hulu',
                'Jongkong Kiri Tengah',
                'Jongkong Pasar',
                'Jongkong Tanjung',
                'Kandung Suli',
                'Karya Baru',
                'Nanga Serian',
                'Penepian Raya',
                'Temenang',
                'Ujung Jambu',
                'Ujung Said',
            ],
            'Kalis' => [
                'Bahenap',
                'Kalis Raya',
                'Kensuray',
                'Nanga Danau',
                'Nanga Kalis',
                'Nanga Lebangan',
                'Nanga Raun',
                'Nanga Sebintang',
                'Nanga Tubuk',
                'Peniung',
                'Rantau Bumbun',
                'Rantau Kalis',
                'Ribang Kadeng',
                'Segiam',
                'Semerantau',
                'Tapang Da`an',
                'Tekudak',
            ],
            'Mentebah' => [
                'Kepala Gurung',
                'Menaren',
                'Nanga Mentebah',
                'Suka Maju',
                'Tangai Jaya',
                'Tanjung',
                'Tanjung Intan',
                'Tekalong',
            ],
            'Pengkadan' => [
                'Buak Limbang',
                'Hulu Pengkadan',
                'Kerangan Panjang',
                'Marta Dana',
                'Mawan',
                'Pengkadan Hilir',
                'Permata',
                'Pinang Laka',
                'Riam Panjang',
                'Sasan',
                'Sira Jaya',
            ],
            'Puring Kencana' => [
                'Kantuk Asam',
                'Kantuk Bunut',
                'Langau',
                'Merakai Panjang',
                'Sungai Antu',
                'Sungai Mawang',
            ],
            'Putussibau Selatan' => [
                'Beringin Jaya',
                'Bungan Jaya',
                'Cempaka Baru',
                'Ingko` Tambe',
                'Jaras',
                'Kedamin Darat',
                'Kereho',
                'Melapi',
                'Sayut',
                'Sungai Uluk',
                'Suka Maju',
                'Tanjung Jati',
                'Tanjung Lokang',
                'Urang Unsa',
                'Kedamin Hilir',
                'Kedamin Hulu',
            ],
            'Putussibau Utara' => [
                'Ariung Mendalam',
                'Banua Tanga',
                'Datah Dian',
                'Jangkang',
                'Lauk',
                'Nanga Awin',
                'Nanga Nyabau',
                'Nanga Sambus',
                'Padua Mendalam',
                'Pala Pulau',
                'Seluan',
                'Sibau Hilir',
                'Sibau Hulu',
                'Sungai Uluk Palin',
                'Tanjung Beruang',
                'Tanjung Karang',
                'Tanjung Lasa',
                'Hilir Kantor',
                'Putussibau Kota',
            ],
            'Seberuang' => [
                'Bati',
                'Bekuan',
                'Belikai',
                'Beluis Harum',
                'Emperiang',
                'Gurung',
                'Jerenjang',
                'Nanga Lot',
                'Nanga Pala',
                'Pala Kota',
                'Ranyai',
                'Sejiram',
                'Seneban',
                'Tajau Mada',
                'Tanjung Keliling',
            ],
            'Selimbau' => [
                'Benuis',
                'Dalam',
                'Engkerengas',
                'Gerayau',
                'Gudang Hilir',
                'Gudang Hulu',
                'Mawan',
                'Nanga Leboyan',
                'Nibung',
                'Piasak Hilir',
                'Piasak Hulu',
                'Sekubah',
                'Sekulat',
                'Semalah',
                'Tempurau',
                'Titian Kuala',
                'Vega',
            ],
            'Semitaul' => [
                'Entipan',
                'Kenepai Komplek',
                'Kenerak',
                'Marsedan Raya',
                'Nanga Kenepai',
                'Nanga Lemedak',
                'Nanga Seberuang',
                'Padung Kumang',
                'Sekedau',
                'Semitau Hilir',
                'Semitau Hulu',
                'Tua` Abang',
            ],
            'Silat Hilir' => [
                'Baru',
                'Bongkong',
                'Bukit Penai',
                'Miau Merah',
                'Nanga Nuar',
                'Pangeran',
                'Penai',
                'Perigi',
                'Rumbih',
                'Seberu',
                'Sungai Sena',
                'Sentabai',
                'Setunggul',
            ],
            'Silat Hulu' => [
                'Belimbing',
                'Dangkan Kota',
                'Entebi',
                'Landau Badai',
                'Landau Rantau',
                'Lebak Nanjah',
                'Nanga Dangkan',
                'Nanga Luan',
                'Nanga Lungu',
                'Nanga Ngeri',
                'Perjuk',
                'Riam Tapang',
                'Selangkai',
                'Selimu',
            ],
            'Suhaid' => [
                'Jongkong Hulu',
                'Kerengas',
                'Laut Tawang',
                'Lubuk Pengail',
                'Madang Permai',
                'Mantan',
                'Menapar',
                'Mensusai',
                'Nanga Suhaid',
                'Tanjung',
                'Tanjung Harapan',
            ],
        ];

        foreach ($data as $districtName => $villages) {

            $district = District::create([
                'regency_id' => $regency->id,
                'name' => $districtName,
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            foreach ($villages as $villageName) {
                Village::create([
                    'district_id' => $district->id,
                    'name' => $villageName,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }
    }
}
