<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Regency;
use App\Models\Village;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KetapangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $regency = Regency::create([
            'name' => 'Kabupaten Ketapang',
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $data = [
            'Air Upas' => [
                'Air Durian Jaya',
                'Air Upas',
                'Banda Sari',
                'Gahang',
                'Harapan Baru',
                'Mekar Jaya',
                'Membuluh Baru',
                'Sari Bekayas',
                'Sukaria',
            ],
            'Benua Kayong' => [
                'Baru',
                'Negeri Baru',
                'Padang',
                'Suka Baru',
                'Sungai Kinjil',
                'Tuan-Tuan',
                'Kauman',
                'Mulia Kerta',
                'Banjar',
                'Kinjil Pesisir',
                'Mekar Sari',
            ],
            'Delta Pawan' => [
                'Kali Nilam',
                'Payah Kumang',
                'Suka Bangun',
                'Suka Bangun Dalam',
                'Kantor',
                'Mulia Baru',
                'Sampit',
                'Suka Harja',
                'Tengah',
            ],
            'Hulu Sungai' => [
                'Batu Lapis',
                'Beginci Darat',
                'Benua Krio',
                'Cinta Manis',
                'Kenyabur',
                'Krio Hulu',
                'Lubuk Kakap',
                'Menyumbung',
                'Riam Dadap',
                'Sekukun',
                'Senduruhan',
                'Sunge Bengaras',
            ],
            'Jelai Hulu' => [
                'Air Dua',
                'Asam Jelai',
                'Bayam Raya',
                'Biku Sarana',
                'Deranuk',
                'Karang Dangin',
                'Kesuma Jaya',
                'Kusik Batu Lapu',
                'Limpang',
                'Pangkalan Paket',
                'Pangkalan Suka',
                'Pasir Mayang',
                'Penyarang',
                'Periangan',
                'Perigi',
                'Rangga Intan',
                'Riam Danau Kanan',
                'Semantun',
                'Sidahari',
                'Tanggerang',
                'Tebing Berseri',
                'Teluk Runjai',
            ],
            'Kendawangan' => [
                'Air Hitam Besar',
                'Air Tarap',
                'Bangkal Serai',
                'Banjar Sari',
                'Danau Buntar',
                'Kendawangan Kanan',
                'Kendawangan Kiri',
                'Pangkalan Batu',
                'Selimantan Jaya',
                'Suka Damai',
                'Suka Harapan',
                'Sungai Jelayan',
                'Air Hitam Hulu',
                'Kedondong',
                'Keramat Jaya',
                'Mekar Utama',
                'Natai Kuini',
                'Pembedilan',
                'Seriam',
            ],
            'Manis Mata' => [
                'Air Dekakah',
                'Asam Besar',
                'Batu Sedau',
                'Bukit Gajah',
                'Jambi',
                'Kelampai',
                'Kelimantan',
                'Kemuning',
                'Lembah Mukti',
                'Manis Mata',
                'Mekar Jaya',
                'Pakit Selaba',
                'Pelempangan',
                'Ratu Elok',
                'Seguling',
                'Sengkuang Merabong',
                'Silat',
                'Suak Burung',
                'Suka Ramai',
                'Sungai Buluh',
                'Terusan',
                'Tribun Jaya',
            ],
            'Marau' => [
                'Bantan Sari',
                'Batu Payung Dua',
                'Belaban',
                'Karya Baru',
                'Pelanjau Jaya',
                'Randai',
                'Rangkung',
                'Riam Batu Gading',
                'Runjai Jaya',
                'Suka Karya',
            ],
            'Matan Hilir Selatan' => [
                'Harapan Baru',
                'Kemuning Biutak',
                'Pagar Mentimun',
                'Pematang Gadung',
                'Pesaguan Kanan',
                'Pesaguan Kiri',
                'Sungai Bakau',
                'Sungai Besar',
                'Sungai Jawi',
                'Sungai Nanjung',
                'Sungai Pelang',
            ],
            'Matan Hilir Utara' => [
                'Kuala Satong',
                'Kuala Tolak',
                'Laman Satong',
                'Sungai Putri',
                'Tanjung Baik Budi',
            ],
            'Muara Pawan' => [
                'Mayak',
                'Sungai Awan Kanan',
                'Sungai Awan Kiri',
                'Suka Maju',
                'Tanjung Pasar',
                'Tanjung Pura',
                'Tempurukan',
                'Ulak Medang',
            ],
            'Nanga Tayap' => [
                'Batu Mas',
                'Betenung',
                'Cegolak',
                'Kayong Hulu',
                'Kayong Utara',
                'Kayong Tuhe',
                'Lembah Hijau Dua',
                'Lembah Hijau Satu',
                'Mensubang',
                'Nanga Tayap',
                'Pangkalan Suka',
                'Pangkalan Teluk',
                'Pateh Benteng',
                'Sebadak Raya',
                'Sungai Kelik',
                'Sepakat Jaya',
                'Siantau Raya',
                'Simpang Tiga Sembelangan',
                'Tajok Kayong',
                'Tanjung Medan',
            ],
            'Pemahan' => [
                'Lalang Panjang',
                'Muara Gerunggang',
                'Pebihingan',
                'Semayok Baru',
                'Usaha Baru',
                'Muara Semayok',
                'Kerta Baru',
            ],
            'Sandai' => [
                'Alam Pakuan',
                'Demit',
                'Istana',
                'Jago Bersatu',
                'Muara Jekak',
                'Merimbang Jaya',
                'Pendamaran Indah',
                'Penjawaan',
                'Petai Patah',
                'Randau',
                'Randau Jungkal',
                'Sandai Kanan',
                'Sandai Kiri',
            ],
            'Simpang Dua' => [
                'Batu Daya',
                'Gema',
                'Kamora',
                'Kampar Sebomban',
                'Mekar Raya',
                'Semandang Kanan',
            ],
            'Singkup' => [
                'Bukit Kelambing',
                'Muntai',
                'Pantai Ketikal',
                'Suka Mulya',
                'Suka Sari',
                'Sukaharja',
                'Sukaraja',
                'Tanah Hitam',
            ],
            'Sungai Laur' => [
                'Bayun Sari',
                'Bengaras',
                'Harapan Baru',
                'Kepari',
                'Lanjut Mekar Sari',
                'Mekar Harapan',
                'Merabu Jaya',
                'Randau Limat',
                'Riam Bunut',
                'Selangkut Raya',
                'Sempurna',
                'Sepotong',
                'Sinar Kuri',
                'Sukaramai',
                'Sungai Daka',
                'Tanjung Beringin',
                'Tanjung Maju',
                'Teluk Bayur',
                'Teluk Mutiara',
            ],
            'Sungai Melayu Rayak' => [
                'Beringin Jaya',
                'Jairan Jaya',
                'Karya Mukti',
                'Kepuluk',
                'Makmur Abadi',
                'Mekar Jaya',
                'Piansak',
                'Suka Mulya',
                'Sungai Melayu',
                'Sungai Melayu Baru',
                'Sungai Melayu Jaya',
            ],
            'Simpang Hulu' => [
                'Balai Pinang',
                'Balai Pinang Hulu',
                'Botuh Bosi',
                'Kenanga',
                'Kualan Hilir',
                'Kualan Hulu',
                'Kualan Tengah',
                'Labai Hilir',
                'Legong',
                'Merawa',
                'Paoh Concong',
                'Sekucing Kualan',
                'Sekucing Labai',
                'Semandang Hulu',
                'Semandang Kiri',
            ],
            'Tumbang Titi' => [
                'Aur Gading',
                'Batu Beransah',
                'Batu Tajam',
                'Belaban Tujuh',
                'Beringin Rayo',
                'Jelayan',
                'Jungkal',
                'Kalimas Baru',
                'Mahawa',
                'Nanga Kelampai',
                'Natai Panjang',
                'Pemuatan Jaya',
                'Pengatapan Raya',
                'Petebang Jaya',
                'Segar Wangi',
                'Sengkaharak',
                'Sepauhan Raya',
                'Sepuring Indah',
                'Serengkah Kanan',
                'Serengkah Kiri',
                'Suka Damai',
                'Tanjung Beulang',
                'Tanjung Maloy',
                'Titi Baru',
                'Tumbang Titi',
            ],
        ];

        foreach ($data as $districtName => $villages) {

            $district = District::create([
                'regency_id' => $regency->id,
                'name' => $districtName,
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            foreach ($villages as $villageName) {
                Village::create([
                    'district_id' => $district->id,
                    'name' => $villageName,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }
    }
}
