<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Regency;
use App\Models\Village;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SintangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $regency = Regency::create([
            'name' => 'Kabupaten Sintang',
            'created_at' => $now,
            'updated_at' => $now,
        ]);

        $data = [
            'Ambalau' => [
                'Bukai Tukun',
                'Bukit Tinggi',
                'Buntut Pimpin',
                'Buntut Purun',
                'Buntut Sabon',
                'Dahtah Bungai',
                'Deme',
                'Jengkarang',
                'Kepala Jungai',
                'Kolangan Juoi',
                'Korong Daso',
                'Lunjan Tingang',
                'Luting Mingan',
                'Mensuang',
                'Nanga Ambalau',
                'Nanga Kemangai',
                'Nanga Keremoi',
                'Nanga Kesange',
                'Nanga Menakon',
                'Nanga Menantak',
                'Nanga Mentomoi',
                'Nanga Pahangan',
                'Nanga Rade',
                'Nanga Sakai',
                'Nanga Sake',
                'Nanga Ukai',
                'Nusa Koring',
                'Patih Jepara',
                'Pulou Sabhang',
                'Purut Beribit',
                'Riam Sabon',
                'Sungai Tambun',
                'Tanjung Andan'
            ],
            'Binjai Hulu' => [
                'Ampar Bedang',
                'Binjai Hilir',
                'Binjai Hulu',
                'Dak Jaya',
                'Empaka Kabiau Raya',
                'Mensiku',
                'Simba Raya',
                'Sungai Risap',
                'Sungai Risap Mensiku Bersatu',
                'Telaga Dua',
                'Telaga Satu'
            ],
            'Dedai' => [
                'Apin Baru',
                'Baras',
                'Batu Landung',
                'Belinyuk Sibau',
                'Dedai Kanan',
                'Empaci',
                'Emparu Baru',
                'Gandis',
                'Gandis Hulu',
                'Hulu Dedai',
                'Jangkang',
                'Kumpang',
                'Lundang Baru',
                'Manaong Baru',
                'Mangat Baru',
                'Manyam',
                'Mengkirai Jaya',
                'Merempit Baru',
                'Nanga Dedai',
                'Nanga Jetak',
                'Pangkadan Sungai Rupa',
                'Pengkadan Baru',
                'Penyak Lalang',
                'Riguk',
                'Samak',
                'Sungai Mali',
                'Sungai Tapang',
                'Tanjung',
                'Taok',
                'Terusan',
                'Umin Jaya'
            ],
            'Kayan Hilir' => [
                'Batu Netak',
                'Begendang Mal',
                'Bukit Segaloh',
                'Buluk Jegara',
                'Buluk Panjang',
                'Engkerangan',
                'Ipoh Emang',
                'Jambu',
                'Jaya Sakti',
                'Karya Baru',
                'Kempas Raya',
                'Kerapa Sepan',
                'Lalang Inggar',
                'Landau Beringin',
                'Lengkong Bindu',
                'Linggam Permai',
                'Mekar Mandiri',
                'Melingkat',
                'Mengkirai',
                'Mentunai',
                'Monbai Begununk',
                'Nanga Lidau',
                'Nanga Mau',
                'Nanga Tikan',
                'Natai Lesung',
                'Natai Tebedak',
                'Neran Baya',
                'Nyangkom',
                'Pakak',
                'Paoh Desa',
                'Pelaik',
                'Sungai Buaya',
                'Sungai Emang',
                'Sungai Garong',
                'Sungai Menuang',
                'Sungai Meraya',
                'Sungai Pengga',
                'Sungai Ranap',
                'Sungai Sintang',
                'Tanjung Keliling',
                'Tanjung Putar',
                'Tertung Mau',
                'Tuguk'
            ],
            'Kayan Hulu' => [
                'Buluh Merindu',
                'Empakan',
                'Emponyang',
                'Entogong',
                'Kebarau',
                'Kerapuk Jaya',
                'Landau Bara',
                'Lintang Tambuk',
                'Mapan Jaya',
                'Merah Arai',
                'Merahau Permai',
                'Nanga Abai',
                'Nanga Laar',
                'Nanga Masau',
                'Nanga Oran',
                'Nanga Payak',
                'Nanga Tampang',
                'Nanga Tebidah',
                'Nanga Tonggoi',
                'Nanga Toran',
                'Nanga Ungai',
                'Nangkak Lestari',
                'Riam Muntik',
                'Riam Panjang',
                'Tanah Merah',
                'Tanjung Bunga',
                'Tanjung Lalau',
                'Tanjung Miru',
                'Tapang Manua',
                'Tonak Goneh',
                'Topan Nanga'
            ],
            'Kelam Permai' => [
                'Baning Panjang',
                'Bengkuang',
                'Ensaid Panjang',
                'Gemba Raya',
                'Karya Jaya Bhakti',
                'Kebong',
                'Kelam Sejahtera',
                'Landau Kodam',
                'Mandiri Jaya',
                'Merpak',
                'Nanga Lebang',
                'Pelimping',
                'Sepan Lebang',
                'Sungai Labi',
                'Sungai Lais',
                'Sungai Maram',
                'Sungai Pukat'
            ],
            'Ketungau Hilir' => [
                'Air Nyuruk',
                'Batu Ampar',
                'Batu Nyadi',
                'Baung Sengatap',
                'Beluh Mulyo',
                'Betung Permai',
                'Bukit Sidin Permai',
                'Jentawang Hilir',
                'Kenuak',
                'Lepung Pantak',
                'Maung',
                'Mungguk Kelapa',
                'Nanga Ketungau',
                'Nanga Merkak',
                'Nanga Sejirak',
                'Pampang Dua',
                'Ratu Damai',
                'Semajau Mekar',
                'Semuntai',
                'Senibung',
                'Setungkup',
                'Sungai Deras',
                'Sungai Mali',
                'Tanjung Baung'
            ],
            'Ketungau Hulu' => [
                'Bekuan Luyang',
                'Embaleh',
                'Empunak Tapang Keladan',
                'Empura',
                'Engkeruh',
                'Idai',
                'Jasa',
                'Muakan Petinggi',
                'Mungguk Entawak',
                'Nanga Bayan',
                'Nanga Bugau',
                'Nanga Sebawang',
                'Neraci Jaya',
                'Rasau',
                'Riam Sejawak',
                'Sebadak',
                'Sebetung Paluk',
                'Sebuluh',
                'Sejawak',
                'Sekaih',
                'Senaning',
                'Sepiluk',
                'Suak Medang',
                'Sungai Bugau',
                'Sungai Kelik',
                'Sungai Mawang',
                'Sungai Pisau',
                'Sungai Seria',
                'Ujung Kempas'
            ],
            'Ketungau Tengah' => [
                'Argo Mulyo',
                'Bakti Senabung',
                'Begelang Jaya',
                'Engkitan',
                'Gut Jaya Bhakti',
                'Kayu Dujung',
                'Kerta Sari',
                'Kubu Berangan',
                'Landau Buaya',
                'Landau Temiang',
                'Margahayu',
                'Mungguk Gelombang',
                'Mungguk Lawang',
                'Nanga Kelapan',
                'Padung Kumang',
                'Panding Jaya',
                'Panggi Agung',
                'Panggi Ruguk',
                'Radin Jaya',
                'Semareh',
                'Senangan Jaya',
                'Senangan Kecil',
                'Sumber Sari',
                'Sungai Areh',
                'Swadaya',
                'Tanjung Sari',
                'Tirta Karya',
                'Wana Bhakti',
                'Wirayuda'
            ],
            'Sepauk' => [
                'Bangun',
                'Bedayan',
                'Bernayau',
                'Buluh Kuning',
                'Ensabang',
                'Gernis Jaya',
                'Kemantan',
                'Kenyauk',
                'Landau Panjang',
                'Lengkenat',
                'Limau Bakti',
                'Mait Hilir',
                'Manis Raya',
                'Nanga Layung',
                'Nanga Libau',
                'Nanga Pari',
                'Nanga Sepauk',
                'Paoh Benua',
                'Peninsung',
                'Riam Kempadik',
                'Sekubang',
                'Sekujam Timbai',
                'Semuntai',
                'Sepulut',
                'Sinar Harapan',
                'Sinar Pekayau',
                'Sirang Setambang',
                'Sukau Bersatu',
                'Sungai Jaung',
                'Sungai Raya',
                'Sungai Segak',
                'Tanjung Balai',
                'Tanjung Hulu',
                'Tanjung Mawang',
                'Tanjung Ria',
                'Tawang Sari',
                'Temawang Bulai',
                'Temawang Muntai',
                'Temiang Kapuas'
            ],
            'Serawai' => [
                'Baras Nabun',
                'Batu Ketebung',
                'Bedaha',
                'Begori',
                'Buntut Ponte',
                'Gurung Senghiang',
                'Karya Jaya',
                'Limbur Bernaung Lestari',
                'Mekar Sari',
                'Mensulung Bio',
                'Mentajoi',
                'Merako Jaya',
                'Meroboi',
                'Muara Kota',
                'Nanga Bihe',
                'Nanga Jelundung',
                'Nanga Mentatai',
                'Nanga Riyoi',
                'Nanga Ruhan',
                'Nanga Segulang',
                'Nanga Serawai',
                'Nanga Tangoi',
                'Nanga Tekungai',
                'Nusa Tujuh',
                'Pagar Lebata',
                'Panekasan',
                'Rantau Malam',
                'Sabhang Landan',
                'Sawang Senghiang',
                'Tahai Permai',
                'Talian Sahabung',
                'Tamakung',
                'Tanjung Baru',
                'Tanjung Harapan',
                'Tanjung Raya',
                'Teluk Harapan',
                'Tontang',
                'Tunas Harapan'
            ],
            'Sintang' => [
                'Akcaya',
                'Alai',
                'Anggah Jaya',
                'Baning Kota',
                'Batu Lalau',
                'Jerora Satu',
                'Kapuas Kanan Hilir',
                'Kapuas Kanan Hulu',
                'Kapuas Kiri Hilir',
                'Kapuas Kiri Hulu',
                'Kebiau Baru',
                'Kedabang',
                'Ladang',
                'Lalang Baru',
                'Mail Jampong',
                'Mekar Jaya',
                'Mengkurai',
                'Menyumbung Tengah',
                'Merti Guna',
                'Mungguk Bantok',
                'Rawa Mambok',
                'Sengkuang',
                'Sungai Ana',
                'Tanjung Kelansam',
                'Tanjung Puri',
                'Tebing Raya',
                'Teluk Kelansam',
                'Tertung',
                'Ulak Jaya'
            ],
            'Sungai Tebelian' => [
                'Balai Agung',
                'Bancoh',
                'Baya Betung',
                'Baya Mulya',
                'Bonet Engkabang',
                'Bonet Lama',
                'Gurung Kempadik',
                'Kajang Baru',
                'Kunyai',
                'Laman Raya',
                'Lebak Ubah',
                'Manter',
                'Melayang Sari',
                'Merarai Dua',
                'Merarai Satu',
                'Nobal',
                'Penjernang',
                'Penjernang Hulu',
                'Perembang',
                'Ransi Dakan',
                'Rarai',
                'Riam Kijang',
                'Sabang Surai',
                'Sarai',
                'Solam Raya',
                'Sungai Ukoi'
            ],
            'Tempunak' => [
                'Balai Harapan',
                'Benua Baru',
                'Benua Kencana',
                'Gurung Mali',
                'Jaya Mentari',
                'Kenyabur Baru',
                'Kuala Tiga',
                'Kupan Jaya',
                'Mengkurat Baru',
                'Mensiap Baru',
                'Mensiap Jaya',
                'Merti Jaya',
                'Nanga Tempunak',
                'Pagal Baru',
                'Pangkal Baru',
                'Pekulai Bersatu',
                'Peribang Baru',
                'Pudau Bersatu',
                'Pulau Jaya',
                'Repak Sari',
                'Riam Batu',
                'Suka Jaya',
                'Sungai Buluh',
                'Tanjung Perada',
                'Tempunak Kapuas',
                'Tinum Baru'
            ]
        ];

        foreach ($data as $districtName => $villages) {

            $district = District::create([
                'regency_id' => $regency->id,
                'name' => $districtName,
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            foreach ($villages as $villageName) {
                Village::create([
                    'district_id' => $district->id,
                    'name' => $villageName,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }
    }
}
